name: app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  dio: ^5.2.1+1
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/WarigariIcon.png

  fonts:
    - family: CarterOneRegular
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf
          weight: 200
        - asset: assets/fonts/CarterOne-Regular.ttf
          weight: 300
        - asset: assets/fonts/CarterOne-Regular.ttf
          weight: 400
        - asset: assets/fonts/CarterOne-Regular.ttf
          weight: 500
        - asset: assets/fonts/CarterOne-Regular.ttf
          weight: 600
        - asset: assets/fonts/CarterOne-Regular.ttf
          weight: 700
        - asset: assets/fonts/CarterOne-Regular.ttf
          weight: 800
        - asset: assets/fonts/CarterOne-Regular.ttf
          weight: 900
